[build]
  # Directory to publish
  publish = "public"
  
  # Build command  
  command = "npm install && chmod +x build.sh && ./build.sh"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node version for functions
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# API proxy (optional - for hiding API endpoints)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Specific page redirects
[[redirects]]
  from = "/dashboard"
  to = "/"
  status = 301

[[redirects]]
  from = "/dashboard.html"
  to = "/"
  status = 301