[build]
  # Directory to publish
  publish = "public"
  
  # Build command  
  command = "npm install && chmod +x build.sh && ./build.sh"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node version for functions
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Redirects
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# API proxy (optional - for hiding API endpoints)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Remove these redirects - they're causing issues
# [[redirects]]
#   from = "/dashboard"
#   to = "/dashboard.html"
#   status = 200

# [[redirects]]
#   from = "/login"
#   to = "/login.html"
#   status = 200

# SPA fallback - only for true 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404